-- MySQL Script generated by MySQL Workbench
-- jue 24 may 2018 19:33:14 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema votaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema votaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `votaciones` DEFAULT CHARACTER SET latin1 ;
USE `votaciones` ;

-- -----------------------------------------------------
-- Table `votaciones`.`organo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`organo` (
  `id_organo` INT(2) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_organo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`rol` (
  `id_rol` VARCHAR(1) NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`facultad` (
  `id_facultad` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_facultad`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`programa` (
  `id_programa` INT(2) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `id_facultad` INT(2) NOT NULL,
  PRIMARY KEY (`id_programa`),
  INDEX `id_facultad` (`id_facultad` ASC),
  CONSTRAINT `programa_ibfk_1`
    FOREIGN KEY (`id_facultad`)
    REFERENCES `votaciones`.`facultad` (`id_facultad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`lugar` (
  `id_lugar` INT(2) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lugar`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`mesa` (
  `id_mesa` INT(3) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `id_lugar` INT(11) NOT NULL,
  PRIMARY KEY (`id_mesa`),
  INDEX `id_lugar` (`id_lugar` ASC),
  CONSTRAINT `mesa_ibfk_1`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `votaciones`.`lugar` (`id_lugar`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`tipo_usuario` (
  `id_tipo_usuario` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`estado_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`estado_usuario` (
  `id_estado_usuario` INT(1) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`usuario` (
  `codigo` INT(12) NOT NULL,
  `nombre1` VARCHAR(30) NOT NULL,
  `nombre2` VARCHAR(30) NOT NULL,
  `apellido1` VARCHAR(30) NOT NULL,
  `apellido2` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `id_tipo_usuario` VARCHAR(3) NOT NULL,
  `id_rol` VARCHAR(1) NOT NULL,
  `id_programa` INT(2) NOT NULL,
  `id_mesa` INT(3) NULL DEFAULT NULL,
  `id_estado_usuario` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`codigo`),
  INDEX `idRol` (`id_rol` ASC),
  INDEX `id_programa` (`id_programa` ASC),
  INDEX `id_mesa` (`id_mesa` ASC),
  INDEX `id_tipo_usuario` (`id_tipo_usuario` ASC),
  INDEX `id_estado_usuario` (`id_estado_usuario` ASC),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `votaciones`.`rol` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usuario_ibfk_3`
    FOREIGN KEY (`id_programa`)
    REFERENCES `votaciones`.`programa` (`id_programa`),
  CONSTRAINT `usuario_ibfk_4`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `votaciones`.`mesa` (`id_mesa`),
  CONSTRAINT `usuario_ibfk_5`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `votaciones`.`tipo_usuario` (`id_tipo_usuario`),
  CONSTRAINT `usuario_ibfk_6`
    FOREIGN KEY (`id_estado_usuario`)
    REFERENCES `votaciones`.`estado_usuario` (`id_estado_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`candidato` (
  `id_candidato` INT(12) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `id_organo` INT(2) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_candidato`),
  INDEX `id_organo` (`id_organo` ASC),
  INDEX `id_candidato` (`id_candidato` ASC),
  CONSTRAINT `candidato_ibfk_1`
    FOREIGN KEY (`id_organo`)
    REFERENCES `votaciones`.`organo` (`id_organo`),
  CONSTRAINT `candidato_ibfk_2`
    FOREIGN KEY (`id_candidato`)
    REFERENCES `votaciones`.`usuario` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `votaciones`.`voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votaciones`.`voto` (
  `id_voto` INT(5) NOT NULL AUTO_INCREMENT,
  `id_mesa` INT(2) NOT NULL,
  `id_candidato` INT(12) NOT NULL,
  `cantidad` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_voto`),
  INDEX `id_mesa` (`id_mesa` ASC),
  INDEX `id_candidato` (`id_candidato` ASC),
  CONSTRAINT `voto_ibfk_1`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `votaciones`.`mesa` (`id_mesa`),
  CONSTRAINT `voto_ibfk_2`
    FOREIGN KEY (`id_candidato`)
    REFERENCES `votaciones`.`candidato` (`id_candidato`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
